org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=true
android.defaults.buildfeatures.buildconfig=true


org.gradle.configureondemand=false
org.gradle.caching=false
android.enableJetifier=true
android.useAndroidX=true

org.gradle.java.home=D:\\dev\\jdk-17
